### ISSUE TITLE
Request for Docker support in Momotok-Server.

### ISSUE THREAD

**Issue by sparkuru** [Shanwer/Momotok-Server#12]
Dear Shanwer:

I hope this message finds you well. I am writing to request the addition of Docker support to Momotok-Server. I believe that introducing Docker containers will greatly enhance the project's flexibility, portability, and ease of deployment for its users.

I am willing to assist in the implementation of Docker support by contributing code, documentation updates, or any other help deemed necessary. Please let me know how I can contribute to this effort.

Thank you for considering my request. Docker support would undoubtedly benefit the project and its community, and I look forward to your positive response.

Sincerely.

**Comment by Shanwer** [comment]
Dear shi9uma,

Thank you for your interest in adding Docker support to Momotok-Server. Your input is greatly appreciated, and I am happy to discuss this with you.

To begin, could you please provide more information about your desired Docker support? What specific architecture of Docker do you hope to integrate into Momotok-Server? Are there any particular use cases or scenarios you have in mind?

Additionally, could you share your technical expertise and familiarity with Docker? Do you have prior experience working with Docker containers and their integration into other systems? I apologize for my lacking experience of programming as I am a beginner of that. Besides, I am currently learning rust and operating system, so that time is precious for me to handle additional work either.

Please note that contributions to Momotok-Server are welcome, and your help in implementing Docker support would be greatly appreciated. However, given the complexity and nature of this work, we may need to establish a more formal collaboration plan and potentially seek out other community members who may be able to assist as well.

Thank you again for your interest in Momotok-Server. I look forward to your response and the opportunity to discuss this further.

Best regards,
Shanwer

**Comment by shi9uma** [comment]
Shanwer,

Thank you for your prompt response. I appreciate your willingness to discuss the addition of Docker support to Momotok-Server. Here are my answers to your questions:

1. Desired Docker Support:
   I would like to integrate a multi-container Docker architecture for Momotalk-Server, separating the momotalk-talk application from a selectable SQL database. This architecture will provide better scalability for the project in the future. Additionally, it would be ideal to publish the application to Docker Hub so that others can easily use and promote Momotok-Server using technologies like Docker Compose.

2. Technical Expertise with Docker:
   I have a good understanding of the principles behind Docker and I have previous experience packaging diverse repositories into Docker containers and migrating them to different hosts. I am confident in my ability to implement Docker support for Momotok-Server and ensure its proper functionality.

3. Additional Suggestion:
   I would like to propose including the project's corresponding APK installation package within the Docker image. This would allow users to download the APK installation directly from a URL and promptly start using Momotok-Server's video streaming capabilities.

Please let me know how I can further assist with the implementation of Docker support for Momotok-Server. I am eagerly looking forward to contributing to the project.

Best regards,
shi9uma

**Comment by sparkuru** [comment]
Kawaii no Shanwer,

Thank you for your prompt response. I appreciate your willingness to discuss the addition of Docker support to Momotok-Server. Here are my answers to your questions:

1. Desired Docker Support:
   I would like to integrate a multi-container Docker architecture for Momotalk-Server, separating the momotalk-talk application from a selectable SQL database. This architecture will provide better scalability for the project in the future. Additionally, it would be ideal to publish the application to Docker Hub so that others can easily use and promote Momotok-Server using technologies like docker-compose.

2. Technical Expertise with Docker:
   I have a good understanding of the principles behind Docker and I have previous experience packaging diverse repositories into Docker containers and migrating them to different hosts. I am confident in my ability to implement Docker support for Momotok-Server and ensure its proper functionality.

3. Additional Suggestion:
   I would like to propose including the project's corresponding APK installation package within the Docker image. This would allow users to download the APK installation directly from a URL and promptly start using Momotok-Server's video streaming capabilities.

Please let me know how I can further assist with the implementation of Docker support for Momotok-Server.I am more than willing to provide support for the project.

vanitas vanitatum et omnia vanitas,
shi9uma

**Comment by Shanwer** [comment]
Shi9uma sama,

Thank you for your continuous attention to the issue, but due to the shortage of time, forgive me for my short reply.

To implement the docker support, you can fork this repository and make commits to your own branch. Before making a pull request, ensure the server operates property and stably. And then you can publish it to Docker Hub. I will provide as much support as I cam provide to you.

domino gratias,
Shanwer

**Comment by sparkuru** [comment]
wagarimashita.
